-- Migration: AI Grading & Plagiarism Fields for Submissions
-- Date: 2026-04-21
-- Adds Gemini AI grading fields and enhanced plagiarism tracking

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS final_score        INTEGER CHECK (final_score >= 0 AND final_score <= 100),
  ADD COLUMN IF NOT EXISTS ai_feedback        TEXT,
  ADD COLUMN IF NOT EXISTS trainer_feedback   TEXT,
  ADD COLUMN IF NOT EXISTS missing_concepts   TEXT,
  ADD COLUMN IF NOT EXISTS plagiarism_percentage NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS plagiarism_status  VARCHAR(30) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS ai_status          VARCHAR(40) DEFAULT 'Pending AI Check',
  ADD COLUMN IF NOT EXISTS trainer_override   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reviewed_by_trainer BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reviewed_at        TIMESTAMP WITH TIME ZONE;

-- Rename ai_score to keep backward compat — add if not exists
ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS ai_score INTEGER CHECK (ai_score >= 0 AND ai_score <= 100);

COMMENT ON COLUMN submissions.final_score          IS 'Final score: equals ai_score unless trainer overrides';
COMMENT ON COLUMN submissions.ai_feedback          IS 'Feedback generated by Gemini AI';
COMMENT ON COLUMN submissions.trainer_feedback     IS 'Feedback written by trainer';
COMMENT ON COLUMN submissions.missing_concepts     IS 'JSON array of missing concepts from Gemini';
COMMENT ON COLUMN submissions.plagiarism_percentage IS 'Cosine similarity % vs other submissions';
COMMENT ON COLUMN submissions.plagiarism_status    IS 'Safe | Warning | High Plagiarism';
COMMENT ON COLUMN submissions.ai_status            IS 'AI Checked | Flagged for Plagiarism | Pending Trainer Review | Finalized';
COMMENT ON COLUMN submissions.trainer_override     IS 'True when trainer has manually set final_score';
COMMENT ON COLUMN submissions.reviewed_by_trainer  IS 'True when trainer has reviewed this submission';
COMMENT ON COLUMN submissions.reviewed_at          IS 'Timestamp of trainer review';
