-- Migration: Add AI grading fields to work_practice_submissions
-- Date: 2026-04-21
-- Mirrors the same fields used in the assignments submissions table

ALTER TABLE work_practice_submissions
  ADD COLUMN IF NOT EXISTS ai_status          VARCHAR(40)    DEFAULT 'Pending AI Check',
  ADD COLUMN IF NOT EXISTS final_score        INTEGER        CHECK (final_score >= 0 AND final_score <= 100),
  ADD COLUMN IF NOT EXISTS ai_feedback        TEXT,
  ADD COLUMN IF NOT EXISTS trainer_feedback   TEXT,
  ADD COLUMN IF NOT EXISTS missing_concepts   TEXT,
  ADD COLUMN IF NOT EXISTS plagiarism_percentage NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS reviewed_by_trainer BOOLEAN       NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reviewed_at        TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS trainer_override   BOOLEAN        NOT NULL DEFAULT false;

COMMENT ON COLUMN work_practice_submissions.ai_status           IS 'Pending AI Check | AI Checked | Finalized | AI Check Failed | Flagged for Plagiarism';
COMMENT ON COLUMN work_practice_submissions.final_score         IS 'Final score: equals ai_score unless trainer overrides';
COMMENT ON COLUMN work_practice_submissions.ai_feedback         IS 'Feedback generated by Groq AI';
COMMENT ON COLUMN work_practice_submissions.trainer_feedback    IS 'Feedback written by trainer';
COMMENT ON COLUMN work_practice_submissions.missing_concepts    IS 'JSON array of missing concepts from AI';
COMMENT ON COLUMN work_practice_submissions.plagiarism_percentage IS 'Cosine similarity % vs other submissions';
COMMENT ON COLUMN work_practice_submissions.reviewed_by_trainer IS 'True when trainer has reviewed this submission';
COMMENT ON COLUMN work_practice_submissions.reviewed_at         IS 'Timestamp of trainer review';
COMMENT ON COLUMN work_practice_submissions.trainer_override    IS 'True when trainer has manually set final_score';
